### ISSUE TITLE
did:peer can't comply with didcommv2

### ISSUE THREAD

**Issue by brianorwhatever** [aviarytech/jff-didcomm-issuance#3]
The service property of did:peer doesn't align with what is required from didcomm v2.. If we go the did:peer approach we will either have to misalign with didcomm or did:peer

**Comment by brianorwhatever** [comment]
I have created a did:peer library that to the best of my knowledge should interoperate with the python did:peer library. If we go this route we can interoperate between typescript & python however it is not conforming to either the did core spec or didcomm v2 spec.

https://github.com/aviarytech/did-peer

**Comment by vongohren** [comment]
@brianorwhatever sorry for not responding, I was primarily following the working sheet.

But is this still an issue? Please add to concerns

**Comment by brianorwhatever** [comment]
I don't think it is an issue anymore it is just sad we don't comply to didcomm v2 service endpoints.. I will be tracking this issue in https://github.com/aviarytech/did-peer/issues/2

**Comment by 2byrds** [comment]
@brianorwhatever can you post some detail about complying with didcomm v2 service endpoints.  i'd like to capture pain points related to did:peer and didcomm v2 since that is the most likely pairing.

**Comment by brianorwhatever** [comment]
yeah it's basically like this:

did:peer service block
```
{
  "type": "DIDCommMessaging",
  "serviceEndpoint": "https://example.com/endpoint",
  "routingKeys": ["did:example:somemediator#somekey"],
  "accept": ["didcomm/v2", "didcomm/aip2;env=rfc587"]
}
```

didcomm v2 service block
```
{
    "id": "did:example:123456789abcdefghi#didcomm-1",
    "type": "DIDCommMessaging",
    "serviceEndpoint": [{
        "uri": "https://example.com/path",
        "accept": [
            "didcomm/v2",
            "didcomm/aip2;env=rfc587"
        ],
        "routingKeys": ["did:example:somemediator#somekey"]
    }]
}
```
