### ISSUE TITLE
How will DID Auth work?

### ISSUE THREAD

**Issue by brianorwhatever** [aviarytech/jff-didcomm-issuance#4]
Proposal:

In the `offer-credential` message the `dif/credential-manifest/manifest@v1.0` attachment contains a `presentation_definition` within the `credential_manifest`, describing the proof `challenge` and proof `domain` for a DID Authentication VP.

The following `request-credential` message has a `dif/credential-manifest/application@v1.0` attachment that is a VP which includes the previously mentioned `challenge` and `domain` in it's proof.

**Comment by vongohren** [comment]
I agree we can go with this way

There was a request from JFF to authenticate the DID that you are issuing to since you potentially are not talking to the same did.

"I want to avoid to issue credentials to a did:peer, so one can share another did when showing the VC"

**Comment by brianorwhatever** [comment]
closed as agreeement has been made. reopen if we want to reconsider
